from odoo.addons.sis_traceability.models import sis_cs
from . import sis_defrost
from . import sis_cutting
from . import sis_cutting_tangki
from . import sis_cutting_basket
from . import sis_cooker_basket
from . import sis_cooker
from . import sis_hr_employee
from . import sis_pre_cleaning
from . import sis_vendor
from . import sis_master_product
from . import sis_crosscheck_cutting
from . import sis_cleaning
from . import sis_packing_supply
from . import sis_packing
from . import sis_retort
from . import sis_retort_loading_basket
from . import sis_unpacking_defrost_loin
from . import sis_ile_whunlabel
from . import sis_wh_bongkar_produk
from . import sis_wh_labeling
# from . import sis_ec_pouch
from . import sis_ec_pouch_hd
from . import sis_traceability
from . import sis_master_reject
