# -*- coding: utf-8 -*-
{
    'name'          : "SIS Bea Cukai",
    'category'      : "",
    'version'       : "1.0.0",
    'depends'       : ["base","hr"],
    'author'        : "IT PT. ATI",
    'description'   : "BC System PT. Aneka Tuna Indonesia",
     'data'          : ["views/sis_hr_employee.xml",
                        "security/Security.xml",
                        "security/ir.model.access.csv",
                        "views/sis_ile.xml",
                        "views/sis_items_category.xml",
                        "views/sis_product_group.xml",
                        "views/sis_location.xml",
                        "views/sis_items_filter.xml",
                        "views/sis_master_filter_bc.xml",
                        "views/sis_laporan_inventory.xml",
                        "views/sis_laporan_document.xml",
                        "views/sis_laporan_document_detail.xml"
                        ],
    "demo"          : [],
    "test"          : [],
    "images"        : [],
    "qweb"          : [],
    "css"           : [],
    "application"   : True,
    "installable"   : True,
    "auto_install"  : False,
}
