# -*- coding: utf-8 -*-
{
    'name'          : "SIS Spec Product",
    'category'      : "",
    'version'       : "1.0.0",
    'depends'       : ["base","hr"],
    'author'        : "IT PT. ATI",
    'description'   : "Spec Product System PT. Aneka Tuna Indonesia",
    'data'          : ["security/security.xml",
                       "security/ir.model.access.csv",
#                        "views/sis_hr_employee.xml",
                       "views/sis_signature.xml",
                       "views/sis_spec_akses.xml",
                       "views/sis_bom.xml",
                       "views/sis_buyer.xml",
                       "reports/sis_print_spec.xml",
                       "reports/sis_report_spec.xml",
                       "views/sis_spec_prod.xml",
                       "views/sis_spec_prod_view.xml"
                       ],
    "demo"          : [],
    "test"          : [],
    "images"        : [],
    "qweb"          : [],
    "css"           : [],
    "application"   : True,
    "installable"   : True,
    "auto_install"  : False,
}